In [1]:
import pandas as pd

In [2]:
pd.read_csv("cars.csv practice")

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,Honda,City,Vx Mt Diesel,"Rs. 13,02,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1272,Honda,City,Zx Mt Diesel,"Rs. 14,21,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1273,Honda,City,Zx Cvt Petrol,"Rs. 14,31,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1274,Honda,City,V Cvt Petrol,"Rs. 12,01,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1275,Mitsubishi,Montero,3.2 At,"Rs. 68,62,560",3200 cc,4.0,4.0,AWD (All Wheel Drive),In-line,BS IV,...,Yes,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

In [3]:
data=pd.read_csv("cars.csv practice")

In [4]:
data.head()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data.isnull()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,False,True,True,True,True,True
1272,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,True,True,True,True,True
1273,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,True,True,True,True,True
1274,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,True,True,True,True,True
1275,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,True,True,True

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Columns: 140 entries, Make to Electric_Range
dtypes: float64(6), object(134)
memory usage: 1.4+ MB

In [7]:
data.isnull().sum()

Make                   75
Model                   0
Variant                 0
Ex-Showroom_Price       0
Displacement           12
                     ...
USB_Ports            1247
Heads-Up_Display     1225
Welcome_Lights       1207
Battery              1263
Electric_Range       1259
Length: 140, dtype: int64

In [8]:
data.head(1)

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Columns: 140 entries, Make to Electric_Range
dtypes: float64(6), object(134)
memory usage: 1.4+ MB

In [10]:
data.describe()

,Cylinders,Valves_Per_Cylinder,Doors,Seating_Capacity,Number_of_Airbags,USB_Ports
count,1210.000000,1174.000000,1272.000000,1270.000000,1141.000000,29.000000
mean,4.380992,3.977853,4.550314,5.270079,3.787029,1.793103
std,1.660957,0.833763,0.747816,1.145231,2.522399,0.773642
min,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000
25%,4.000000,4.000000,4.000000,5.000000,2.000000,1.000000
50%,4.000000,4.000000,5.000000,5.000000,2.000000,2.000000
75%,4.000000,4.000000,5.000000,5.000000,6.000000,2.000000
max,16.000000,16.000000,5.000000,16.000000,14.000000,3.000000

In [11]:
data['Make'].unique

<bound method Series.unique of 0             Tata
1             Tata
2             Tata
3             Tata
4             Tata
           ...
1271         Honda
1272         Honda
1273         Honda
1274         Honda
1275    Mitsubishi
Name: Make, Length: 1276, dtype: object>

In [12]:
data['Make'].value_counts()

Make
Maruti Suzuki       149
Hyundai             130
Mahindra            119
Tata                100
Toyota               82
Honda                64
Ford                 43
Skoda                43
Bmw                  37
Renault              36
Volkswagen           34
Audi                 31
Nissan               29
Jeep                 28
Land Rover Rover     27
Fiat                 23
Jaguar               22
Kia                  21
Volvo                18
Datsun               15
Maruti Suzuki R      14
Porsche              14
Mg                   13
Lamborghini          13
Icml                 11
Mini                 10
Land Rover           10
Lexus                10
Maserati              9
Ferrari               8
Mitsubishi            7
Premier               6
Bentley               6
Force                 6
Isuzu                 5
Aston Martin          3
Bugatti               2
Bajaj                 2
Dc                    1
Name: count, dtype: int64

In [13]:
data['USB_Ports']=data['USB_Ports'].fillna(data['USB_Ports'].mean())

In [14]:
data['Make']=data['Make'].fillna('Maruti Suzuki ',inplace=False)

In [15]:
data.isnull().sum()

Make                    0
Model                   0
Variant                 0
Ex-Showroom_Price       0
Displacement           12
                     ...
USB_Ports               0
Heads-Up_Display     1225
Welcome_Lights       1207
Battery              1263
Electric_Range       1259
Length: 140, dtype: int64

In [16]:
data['Make'].isnull().sum()

np.int64(0)

In [17]:
data['Make'].unique()

array(['Tata', 'Datsun', 'Renault', 'Maruti Suzuki', 'Hyundai', 'Premier',
       'Toyota', 'Nissan', 'Volkswagen', 'Ford', 'Mahindra', 'Fiat',
       'Honda', 'Jeep', 'Isuzu', 'Skoda', 'Audi', 'Maruti Suzuki ', 'Dc',
       'Mini', 'Volvo', 'Jaguar', 'Bmw', 'Land Rover', 'Porsche', 'Lexus',
       'Maserati', 'Lamborghini', 'Bentley', 'Ferrari', 'Aston Martin',
       'Bugatti', 'Bajaj', 'Icml', 'Force', 'Mg', 'Kia',
       'Land Rover Rover', 'Mitsubishi', 'Maruti Suzuki R'], dtype=object)

In [18]:
data['Make'].value_counts()

Make
Maruti Suzuki       149
Hyundai             130
Mahindra            119
Tata                100
Toyota               82
Maruti Suzuki        75
Honda                64
Skoda                43
Ford                 43
Bmw                  37
Renault              36
Volkswagen           34
Audi                 31
Nissan               29
Jeep                 28
Land Rover Rover     27
Fiat                 23
Jaguar               22
Kia                  21
Volvo                18
Datsun               15
Maruti Suzuki R      14
Porsche              14
Mg                   13
Lamborghini          13
Icml                 11
Mini                 10
Land Rover           10
Lexus                10
Maserati              9
Ferrari               8
Mitsubishi            7
Premier               6
Bentley               6
Force                 6
Isuzu                 5
Aston Martin          3
Bugatti               2
Bajaj                 2
Dc                    1
Name: count, dtype: int64

In [19]:
data.head()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,NaN,NaN,NaN,NaN

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Columns: 140 entries, Make to Electric_Range
dtypes: float64(6), object(134)
memory usage: 1.4+ MB

In [21]:
data.shape

(1276, 140)

In [22]:
data.columns

Index(['Make', 'Model', 'Variant', 'Ex-Showroom_Price', 'Displacement',
       'Cylinders', 'Valves_Per_Cylinder', 'Drivetrain',
       'Cylinder_Configuration', 'Emission_Norm',
       ...
       'Leather_Wrapped_Steering', 'Automatic_Headlamps', 'Engine_Type',
       'ASR_/_Traction_Control', 'Cruise_Control', 'USB_Ports',
       'Heads-Up_Display', 'Welcome_Lights', 'Battery', 'Electric_Range'],
      dtype='object', length=140)

In [23]:
data.isnull().sum()

Make                    0
Model                   0
Variant                 0
Ex-Showroom_Price       0
Displacement           12
                     ...
USB_Ports               0
Heads-Up_Display     1225
Welcome_Lights       1207
Battery              1263
Electric_Range       1259
Length: 140, dtype: int64

In [24]:
data['Heads-Up_Display'].unique()

array([nan, 'Yes'], dtype=object)

In [25]:
data['Heads-Up_Display'].value_counts()

Heads-Up_Display
Yes    51
Name: count, dtype: int64

In [26]:
data['Heads-Up_Display'].fillna('yes', inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\3659487814.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Heads-Up_Display'].fillna('yes', inplace=True)

In [27]:
data['Heads-Up_Display'].isnull().sum()

np.int64(0)

In [28]:
data['Make']=data['Make'].fillna('Maruti Suzuki ',inplace=False)

In [29]:
data.isnull().sum()

Make                    0
Model                   0
Variant                 0
Ex-Showroom_Price       0
Displacement           12
                     ...
USB_Ports               0
Heads-Up_Display        0
Welcome_Lights       1207
Battery              1263
Electric_Range       1259
Length: 140, dtype: int64

In [30]:
data['Welcome_Lights'].unique()

array([nan, 'Yes'], dtype=object)

In [31]:
data['Welcome_Lights'].value_counts()

Welcome_Lights
Yes    69
Name: count, dtype: int64

In [32]:
data['Welcome_Lights'].fillna('yes',inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\1256795697.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Welcome_Lights'].fillna('yes',inplace=True)

In [33]:
data['Welcome_Lights'].isnull().sum()

np.int64(0)

In [34]:
data['Battery'].unique()

array([nan, '210 ampere-hour', '21.5 kWh,Battery Placed Under Rear Seats',
       '200 ampere-hour', '44.5 (kWh), Lithium Ion',
       '30.2 kWh* Advanced Li-ion polymer, liquid cooled battery pack with IP67 certification'],
      dtype=object)

In [35]:
data['Battery'].value_counts()

Battery
21.5 kWh,Battery Placed Under Rear Seats                                                 3
30.2 kWh* Advanced Li-ion polymer, liquid cooled battery pack with IP67 certification    3
200 ampere-hour                                                                          3
210 ampere-hour                                                                          2
44.5 (kWh), Lithium Ion                                                                  2
Name: count, dtype: int64

In [36]:
data['Battery'].fillna('200 ampere-hour',inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\2790763518.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Battery'].fillna('200 ampere-hour',inplace=True)

In [37]:
data['Battery'].isnull().sum()

np.int64(0)

In [38]:
data['Displacement'].unique()

array(['624 cc', '799 cc', '999 cc', '1196 cc', '998 cc', '1198 cc',
       '1086 cc', '1199 cc', '1197 cc', '1173 cc', '1489 cc', '1248 cc',
       '1364 cc', '1193 cc', '1396 cc', '1186 cc', '1498 cc', '1194 cc',
       '1496 cc', '1461 cc', '1368 cc', '1956 cc', '2999 cc', '2157 cc',
       '1968 cc', '1997 cc', '1597 cc', '1798 cc', '1395 cc', '1595 cc',
       '2143 cc', '1991 cc', '2000 cc', '1998 cc', '1969 cc', '1999 cc',
       '1984 cc', '1995 cc', '2995 cc', '2993 cc', '2998 cc', '4951 cc',
       '2987 cc', '6417 cc', '3604 cc', '2996 cc', '2979 cc', '1988 cc',
       '5461 cc', '2982 cc', '3456 cc', '2894 cc', '6592 cc', '3982 cc',
       '2925 cc', '4691 cc', '5980 cc', '4663 cc', '3996 cc', '4461 cc',
       '5204 cc', '5998 cc', '3855 cc', '5950 cc', '5198 cc', '4497 cc',
       '6593 cc', '6752 cc', '6750 cc', '6749 cc', '7993 cc', '216 cc',
       '796 cc', '1120 cc', '1497 cc', '1994 cc', '1298 cc', '1397 cc',
       '1493 cc', '2523 cc', '1591 cc', '1582 cc', '1598 cc', nan,
       '2498 cc', '2596 cc', '2149 cc', '1462 cc', '2179 cc', '72 cc',
       '2393 cc', '2694 cc', '2755 cc', '1799 cc', '2199 cc', '3198 cc',
       '2198 cc', '2400 cc', '1950 cc', '2967 cc', '4999 cc', '4367 cc',
       '3993 cc', '3902 cc', '3900 cc', '6262 cc', '6498 cc', '6598 cc',
       '1172 cc', '2489 cc', '1353 cc', '1500 cc', '1596 cc', '2487 cc',
       '2494 cc', '2981 cc', '3799 cc', '5935 cc', '6496 cc', '2499 cc',
       '1898 cc', '2360 cc', '1993 cc', '4395 cc', '5000 cc', '5700 cc',
       '1047 cc', '2200 cc', '2477 cc', '3200 cc'], dtype=object)

In [39]:
data['Displacement'].value_counts()

Displacement
1197 cc    108
1498 cc     87
1248 cc     62
1198 cc     58
1497 cc     56
          ...
1993 cc      1
5700 cc      1
1047 cc      1
2200 cc      1
3200 cc      1
Name: count, Length: 129, dtype: int64

In [40]:
data['Electric_Range'].unique()

array([nan, '39.53 km/full charge', '110 km/full charge',
       '213 km/full charge', '340 km/full charge', '11.68 km/full charge',
       '312 km/full charge', '300 km/full charge', '462 km/full charge'],
      dtype=object)

In [41]:
data['Electric_Range'].value_counts()

Electric_Range
110 km/full charge      5
213 km/full charge      3
340 km/full charge      2
11.68 km/full charge    2
312 km/full charge      2
39.53 km/full charge    1
300 km/full charge      1
462 km/full charge      1
Name: count, dtype: int64

In [42]:
data['Electric_Range'].fillna(method='ffill',inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\3365196243.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Electric_Range'].fillna(method='ffill',inplace=True)
C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\3365196243.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Electric_Range'].fillna(method='ffill',inplace=True)

In [43]:
data['Electric_Range'].isnull().sum()

np.int64(319)

In [44]:
data.isnull().sum()

Make                   0
Model                  0
Variant                0
Ex-Showroom_Price      0
Displacement          12
                    ...
USB_Ports              0
Heads-Up_Display       0
Welcome_Lights         0
Battery                0
Electric_Range       319
Length: 140, dtype: int64

In [45]:
data.head()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,yes,yes,200 ampere-hour,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,yes,yes,200 ampere-hour,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,yes,yes,200 ampere-hour,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,yes,yes,200 ampere-hour,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,1.793103,yes,yes,200 ampere-hour,NaN

In [46]:
data['Leather_Wrapped_Steering'].unique()

array([nan, 'Yes'], dtype=object)

In [47]:
data['Leather_Wrapped_Steering'].value_counts()

Leather_Wrapped_Steering
Yes    587
Name: count, dtype: int64

In [48]:
data['Leather_Wrapped_Steering'].fillna('yes ',inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\2250075964.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Leather_Wrapped_Steering'].fillna('yes ',inplace=True)

In [49]:
data['Leather_Wrapped_Steering'].isnull().sum()

np.int64(0)

In [50]:
data['Automatic_Headlamps'].unique()

array([nan, 'Yes'], dtype=object)

In [51]:
data['Automatic_Headlamps'].value_counts()

Automatic_Headlamps
Yes    502
Name: count, dtype: int64

In [52]:
data['Automatic_Headlamps'].fillna('yes ',inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\1276874225.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Automatic_Headlamps'].fillna('yes ',inplace=True)

In [53]:
data['Automatic_Headlamps'].isnull().sum()

np.int64(0)

In [54]:
data['Engine_Type'].unique()

array([nan, '2.0 Diesel',
       'Roller cam follower, continuous intake and exhaust camshaft adjustment, hydraulic valve-play compensation / 2/2 inlet/exhaust valves per cylinder',
       '1.2 L Revotron (BS VI)', '1.5L Turbocharged Revotorq (BS VI)',
       'Revotron 1.2 L, BS6 Engine', 'M1 Category', 'CRDi', 'D180',
       'P 250', 'Biturbo engine', '9G-TRONIC'], dtype=object)

In [55]:
data['Engine_Type'].value_counts().sum()

np.int64(34)

In [56]:
data['Engine_Type'].fillna(method='bfill',inplace=True)

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\4150238755.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Engine_Type'].fillna(method='bfill',inplace=True)
C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\4150238755.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Engine_Type'].fillna(method='bfill',inplace=True)

In [57]:
data['Engine_Type'].isnull().sum()

np.int64(227)

In [58]:
data.isnull().any()

Make                 False
Model                False
Variant              False
Ex-Showroom_Price    False
Displacement          True
                     ...
USB_Ports            False
Heads-Up_Display     False
Welcome_Lights       False
Battery              False
Electric_Range        True
Length: 140, dtype: bool

In [59]:
data['Displacement'].fillna('624cc',inplace=True )

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\922598848.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Displacement'].fillna('624cc',inplace=True )

In [60]:
data['Displacement'].isnull().sum()

np.int64(0)

In [61]:
data['ASR_/_Traction_Control'].unique()

array([nan, 'Yes'], dtype=object)

In [62]:
data['ASR_/_Traction_Control'].value_counts()

ASR_/_Traction_Control
Yes    442
Name: count, dtype: int64

In [63]:
data['ASR_/_Traction_Control'].fillna(method='bfill',inplace=True )

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\1161863675.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['ASR_/_Traction_Control'].fillna(method='bfill',inplace=True )
C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\1161863675.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['ASR_/_Traction_Control'].fillna(method='bfill',inplace=True )

In [64]:
data['ASR_/_Traction_Control'].isnull().sum()

np.int64(0)

In [65]:
data['Cruise_Control'].unique()

array([nan, 'Yes'], dtype=object)

In [66]:
data['Cruise_Control'].fillna(method='bfill',inplace=True )

C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\1553576079.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Cruise_Control'].fillna(method='bfill',inplace=True )
C:\Users\abbas\AppData\Local\Temp\ipykernel_19372\1553576079.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Cruise_Control'].fillna(method='bfill',inplace=True )

In [67]:
data['Cruise_Control'].isnull().sum()

np.int64(0)

In [68]:
data.isnull().sum()

Make                   0
Model                  0
Variant                0
Ex-Showroom_Price      0
Displacement           0
                    ...
USB_Ports              0
Heads-Up_Display       0
Welcome_Lights         0
Battery                0
Electric_Range       319
Length: 140, dtype: int64